### ISSUE TITLE
API definition

### ISSUE THREAD

**Issue by micheleriva** [LyraSearch/nebula#1]
Nebula will be the build tool for Lyra. It will allow the database to run on every runtime and network.
This issue aims to discuss the usage and APIs for the building system.

# YAML config

```yaml
version: 0.1

schema:
  definition:
    title: string
    year: number
    cast:
      director: string
      main: string

sharding: auto

target:
  platform: cloudflare
  tests: true

data:
  source: ./get-data.mjs
```
